### ISSUE TITLE
How should `trace` interact with lazy mode?

### ISSUE THREAD

**Issue by usaoc** [mflatt/shplait#3]
The `trace` form currently doesn’t work with functions defined in lazy mode (lacking a `dynamic_force`).  However, a more severe problem is that (printing in) tracing will force any argument/result thunk, which is arguably undesirable.

**Comment by mflatt** [comment]
As of the latest commit, I think lazy mode is defined much better, and its interaction with `trace` is now reasonable and useful. I'll lave this issue open for now, though, in case you have more thoughts.

**Comment by usaoc** [comment]
One more thing I’ve noticed: printing can potentially expose the underlying representation.  For example:

```
#lang shplait
~lazy

fun lazy_map(f :: ?a -> ?b, lst :: Listof(?a)) :: Listof(?b):
  match lst
  | []: []
  | cons(hd, tl): cons(f(hd), lazy_map(f, tl))

> lazy_map(add1, [1, 2, 3])
- Listof(Number)
cons(2, cons(3, cons(4, [])))
```

This is probably specific to lists, where the `Lazy` wrapper makes the pair fail `list?`.

Edit: Update example.

**Comment by usaoc** [comment]
Possible confusion in the specification: functions like `map` behave only as lazily as the argument function does, in the sense that the list is still processed eagerly.

Edit: This is due to a bug in `is_lazy`, because a defined lazy function is wrapped in `Traceable`.

**Comment by mflatt** [comment]
Right, thanks! Commit 7564a1f31617f40a95cf880b620989c35e0cedf9 tries a different strategy for lazy library functions like `map`.

**Comment by usaoc** [comment]
Lazy library functions now work as expected.  Regarding the printing of lazy lists, I’ve tracked down the issue to two places: 1. `describe` of `Lazy` should use `dynamic_force_all` (and optimally save the result), and 2. `dynamic_force_all` should use `Pair.cons` (at least in the pattern), because the `Lazy` wrapper can make the tail a non `List`.

**Comment by mflatt** [comment]
Thank you for the printing repair!

**Comment by usaoc** [comment]
I’ve realized another unfortunate oversight:

```
#lang shplait
~lazy

> cons(1, cons(2, []))
- Listof(Number)
cons(1, [2])
> print(cons(1, cons(2, [])))
- Void
[1, 2]
```

Module-level expressions are not wrapped in `Lazy` as arguments are, therefore not `dynamic_force_all`ed.

**Comment by mflatt** [comment]
I'm not sure, but the right idea might be to configure `current-print` as part of the language's runtime configuration. (Rhombus needs to be more flexible there, since it currently always adds its own `configure-runtime` submodule.)

**Comment by usaoc** [comment]
I’m closing the issue as the original problem (tracing and printing of lazy values in general) seems to have been resolved.  Other problems about lazy mode, if any, can be left to new issues.
